### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by rossman22590** [Cadogy/ChatGPT-Clone-V2#1]
error 500 on API

**Comment by rossman22590** [comment]
sorry mad mistake please cancel my pull requests.

**Comment by rossman22590** [comment]
any reason why error 500 on the askquestions.ts? everything else works

**Comment by charlesknapp** [comment]
@rossman22590 API has been resolved. However, your own firebase shouldn't cause any issues.

**Comment by rossman22590** [comment]
does it work with GPT4?
